### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by Alexandr21Smirnov** [Alexandr21Smirnov/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Alexandr21Smirnov21collaborator** [comment]
#### Donald Trump

-[DonaldTrump - facebook](https://www.fb.com/DonaldTrump)
-[DonaldTrump - twitter](https://twitter.com/realDonaldTrump)
-[DonaldTrump - instagram](https://www.instagram.com/realDonaldTrump/)
-[DonaldTrump - whitehouse](realDonaldTrump@whitehouse.gov)

**Comment by Alexandr21Smirnov** [comment]
I need it?
