### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by Alexandr21Smirnov** [Alexandr21Smirnov/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by Alexandr21Smirnov21collaborator** [comment]
**PERSONAL LIFE**

***Early life***

1946 
I'm was born (Finally)

1964
Enrolled at Fordham University (Why me)

1966
Transferred to the Wharton School of the University of Pennsylvania (Here were go againg)

1966
I was deemed fit for military service based upon a medical examination (Cool story)

1968
Graduated with a B.S. in economics (Really?)

***Family***

1977
Married Czech model Ivana Zelníčková (Yep)

1977
My first son is born. I called him Donald (Anyway)

1982
Birth of Ivanka Trump(I want to called Donald too, but wife...)

1984
Birth of Eric Trump(I'm very liked Eric Clapton)

1992
Affair with actress Marla Maples and divorce Ivana (Double kill)

1993
Married Marla and had a daughter, we named her Tiffany (Cause I can)

1999
Divorced Marla (So bad)



1964
Enrolled at Fordham University 
1966
Transferred to the Wharton School of the University of Pennsylvania

**Comment by Alexandr21Smirnov** [comment]
That was.. comical
