### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by Alexandr21Smirnov** [Alexandr21Smirnov/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by Alexandr21Smirnov21collaborator** [comment]
LANGUAGES
🇺🇸 ENGLISH 🇷🇺 РУССКИЙ(native)

SKILLS :basecampy:
Earning, Marrieding, Advertising my haircut, Reporting everyone, Suing with haters, Investing like Warren Buffett,Twiting with Obama, Hiding that I'm russinan, Naming everything like my surname, Dancing, Sleeping, Dancing while Sleeping, Swimming like a Michael Phelps, Diving, Climbing, Writing like Shakespeare, Look menacing like myself, Singing like Pavarotti, Cooking like Gordon Ramsay, Coding like Solo - and that just for Monday

CHARACTER 👱‍♂️ 
First of all Handsome, Wise, Recursive, Persistent, Gentle, Calm, Furious, Leader, Timid, Сommunicable, Introvert, Prudent, Self-critical, Funny, Serious, Brave, Monogamous, Lonely, Curious, Competetive, Clever, etc.

LIKES 😏
Money, Models, Yachts, Simplicity, Power, Сapitalism, Binary options, Wrestling, Diet cola, Сheeseburgers, Birthdays, TV,
Own surname, Family

DISLIKES 😔
Dogs, Sharks, Protests, Immigrants, Liberals, Democracy, Mexicans, Iraq, Wind

WANTS 😵
Live forever, Become a president of United States second time, Create own social network, Have a healty family
